# Generated by Django 2.1 on 2018-08-05 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('sale', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='pricetracking',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery_manager.Item'),
        ),
    ]
